## Write to existing file
file = paste('_docs', label_name, label_run, 'summary.md', sep = '//')
cat(paste('### Methods', '\n', sep = ''), file = file, append = TRUE)
cat(paste(desc_methods, '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('Data for this study was collected from the ', reference, '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('\n', sep = ''), file = file, append = TRUE)
cat(paste('#### Variable Definitions: \n', sep = ''), file = file, append = TRUE)
cat(paste('`count` ', 'Raw count of ', full, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('`log` ', desc_log, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('`crude3` ', desc_crude3, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('`ZDI` ', desc_ZDI, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('`age` ', desc_age, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('`sex` ', desc_sex, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('`race` ', desc_race, '\n\n', sep = ''), file = file, append = TRUE) 
cat(paste('\n', sep = ''), file = file, append = TRUE)
cat(paste('#### Variable Notes: \n', sep = ''), file = file, append = TRUE)
cat(paste(notes, '\n', sep = ''), file = file, append = TRUE)
cat(paste('\n', sep = ''), file = file, append = TRUE)
cat('#### OLS Assumption Tests (Y = ', Y, '):\n\n', file = file, append = TRUE)
cat(capture.output(utt), file = file, append = TRUE)
cat('(Significant = Non-linearity)\n\n', file = file, append = TRUE)
cat(capture.output(jb), file = file, append = TRUE)
cat('(Significant = Non-normal)\n\n', file = file, append = TRUE)
cat(capture.output(ad), file = file, append = TRUE)
cat('(Significant = Non-normal)\n\n', file = file, append = TRUE)
cat(capture.output(dw), file = file, append = TRUE)
cat('(Significant = Auto-correlation)\n',  file = file, append = TRUE)
cat(capture.output(bp), file = file, append = TRUE)
cat('(Significant = Homoscedastic)\n\n', file = file, append = TRUE)
cat(capture.output(gq), file = file, append = TRUE)
cat('(Significant = Heteroscedastic)\n\n', file = file, append = TRUE)
cat('\n', file = file, append = TRUE)
cat(paste('### Results', '\n', sep = ''), file = file, append = TRUE) 
cat(paste('#### Univariate Statistics (Median values):\n', sep = ''), file = file, append = TRUE)
cat(paste('count = ', median(df_WXY$count), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('log = ', median(df_WXY$log), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('crude3 = ', median(df_WXY$crude3), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('ZDI = ', median(df_WXY$ZDI), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('age = ', median(df_WXY$age), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('sex = ', median(df_WXY$sex), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('race = ', median(df_WXY$race), '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('\n', sep = ''), file = file, append = TRUE)
cat(paste('#### Bivariate Statistics (Y = ', Y, '):\n', sep = ''), file = file, append = TRUE)
cat(paste('ZDI = ', cor_ZDI, '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('age = ', cor_age, '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('sex = ', cor_sex, '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('race = ', cor_race, '\n\n', sep = ''), file = file, append = TRUE)
cat(paste('\n', sep = ''), file = file, append = TRUE)
cat('#### Regression Models (Y = ', Y, '): \n\n', file = file, append = TRUE)
cat('\n', file = file, append = TRUE)
cat(paste(str_replace_all(capture.output(GWR), c(''' = '', ''' = '')), '\n\n', sep = ''), file = file, append = TRUE)
cat('\n', file = file, append = TRUE)
cat('### Tables and Figures\n\n', file = file, append = TRUE)
cat(paste('![](', ST, '_', target, '_resid_plot.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_QQ_plot.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_cor_plot.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_count_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_log_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_crude3_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_ZDI_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_GWR_ZDI_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_age_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_sex_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('![](', ST, '_', target, '_race_map.png)\n\n', sep = ''), file = file, append = T)
cat(paste('########################################\n\n', 
          'Last Update: ', stamp, ' by ', user, '<br>\n',
          'Disclaimer: ', disclaimer, '\n',
          '\n', sep = ''), file = file, append = TRUE)

### COnvert Markdown to HTML/Word
render(input = file, output_format = 'html_document',  output_file = paste(ST, '_', target, '_page.html', sep = ''))
render(input = file, output_format = 'word_document',  output_file = paste(ST, '_', target, '_report.doc', sep = ''))